### ISSUE TITLE
Hey.

### ISSUE THREAD

**Issue by HamzaAnis** [MohammedRashad/SolidCoin#1]
I want to know what is this repo about? if you have plans for it. I want to contribute.

**Comment by MohammedRashad** [comment]
I'm making a new coin (token) based on etherum built over solidity, I'm planning to publish an ICO or something maybe, and yes I have big plans for it.

**Comment by HamzaAnis** [comment]
OK cool.
Ping me when you will start it. I'll be very happy to contribute in this.
